[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Anurag Prajapati", email = "prajapatianurag73240@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.141.1",
    "psycopg2>=2.9.12",
    "sqlalchemy>=2.0.51",
    "uvicorn[standard]>=0.52.1",
]



