"""file path and file type columns in documents table

Revision ID: 4f871fc6a3fd
Revises: 9bb325b66bcd
Create Date: 2026-08-13 19:17:38.559357

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4f871fc6a3fd"
down_revision: str | Sequence[str] | None = "9bb325b66bcd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documents", sa.Column("file_path", sa.String(length=255), nullable=False)
    )
    op.add_column(
        "documents", sa.Column("file_type", sa.String(length=10), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "file_type")
    op.drop_column("documents", "file_path")
    # ### end Alembic commands ###
