"""chunks db table

Revision ID: 68c461fdbcfb
Revises: 4f871fc6a3fd
Create Date: 2026-08-14 15:08:57.552875

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "68c461fdbcfb"
down_revision: str | Sequence[str] | None = "4f871fc6a3fd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
