"""description column in kb

Revision ID: 732d2fe4bd9d
Revises: 416f2a087ddc
Create Date: 2026-08-15 11:38:17.253462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '732d2fe4bd9d'
down_revision: Union[str, Sequence[str], None] = '416f2a087ddc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_bases', sa.Column('description', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_bases', 'description')
    # ### end Alembic commands ###
