"""foreign key childrene cascade

Revision ID: 7b09ab479c2d
Revises: 05eb4c3ddd09
Create Date: 2026-08-13 16:14:38.884711

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7b09ab479c2d"
down_revision: str | Sequence[str] | None = "05eb4c3ddd09"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documents",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "documents",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.drop_constraint(op.f("documents_kb_id_fkey"), "documents", type_="foreignkey")
    op.create_foreign_key(
        None,
        "documents",
        "knowledge_bases",
        ["kb_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("knowledge_bases_user_id_fkey"), "knowledge_bases", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "knowledge_bases",
        "users",
        ["user_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "knowledge_bases", type_="foreignkey")
    op.create_foreign_key(
        op.f("knowledge_bases_user_id_fkey"),
        "knowledge_bases",
        "users",
        ["user_id"],
        ["id"],
    )
    op.drop_constraint(None, "documents", type_="foreignkey")
    op.create_foreign_key(
        op.f("documents_kb_id_fkey"), "documents", "knowledge_bases", ["kb_id"], ["id"]
    )
    op.drop_column("documents", "updated_at")
    op.drop_column("documents", "created_at")
    # ### end Alembic commands ###
