"""doc status column

Revision ID: 9bb325b66bcd
Revises: 7b09ab479c2d
Create Date: 2026-08-13 17:19:25.539477

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9bb325b66bcd"
down_revision: str | Sequence[str] | None = "7b09ab479c2d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documents", sa.Column("doc_status", sa.String(length=100), nullable=False)
    )
    op.add_column("documents", sa.Column("user_id", sa.Integer(), nullable=False))
    op.create_foreign_key(
        None,
        "documents",
        "users",
        ["user_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "documents", type_="foreignkey")
    op.drop_column("documents", "user_id")
    op.drop_column("documents", "doc_status")
    # ### end Alembic commands ###
